services:
  rustretail.identityservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__IdentityDatabase=Host=rustretail.identityservice.postgres;Port=5432;Database=rustretail_identityservice;Username=postgres;Password=postgres
      - Jwt__Issuer=${Jwt__Issuer}
      - Jwt__Audience=${Jwt__Audience}
      - Jwt__SecretKey=${Jwt__SecretKey}
      - RabbitMQ__Host=${RabbitMQ__Host}
    ports:
      - "8080:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro